# Generated by Django 2.1.7 on 2019-07-22 15:16

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth', models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(2019), django.core.validators.MinValueValidator(1920)])),
                ('is_male', models.BooleanField(blank=True)),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='profile_img')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notichecked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('religion', models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(4), django.core.validators.MinValueValidator(1)])),
                ('left_level', models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('major', models.CharField(blank=True, max_length=3)),
                ('region', models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(8), django.core.validators.MinValueValidator(1)])),
                ('recent_login', models.DateTimeField(default=django.utils.timezone.now)),
                ('likes_iphone', models.BooleanField(blank=True)),
                ('is_premium', models.BooleanField(default=False)),
                ('is_first_login', models.BooleanField(default=True)),
                ('is_facebook', models.BooleanField(default=True)),
                ('follows', models.ManyToManyField(blank=True, through='accounts.Follow', to='accounts.Profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='follow',
            name='follow_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_from', to='accounts.Profile'),
        ),
        migrations.AddField(
            model_name='follow',
            name='follow_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_to', to='accounts.Profile'),
        ),
    ]
