# Generated by Django 2.1.7 on 2019-04-26 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='major',
            field=models.CharField(default='기타', max_length=3),
        ),
    ]
