# Generated by Django 2.1.7 on 2019-05-21 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='/static/feedpage/default_avatar.png', upload_to='blah'),
        ),
    ]
