# Generated by Django 2.1.7 on 2019-05-27 06:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='notichecked_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
