# Generated by Django 2.1.7 on 2019-04-30 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190427_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='follows',
            field=models.ManyToManyField(blank=True, through='accounts.Follow', to='accounts.Profile'),
        ),
    ]
