# Generated by Django 2.1.7 on 2019-06-20 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190621_0115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='is_heavy',
            new_name='is_premium',
        ),
    ]
