# Generated by Django 2.1.7 on 2019-06-23 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20190623_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='left_level',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='region',
            field=models.IntegerField(),
        ),
    ]
