# Generated by Django 2.1.7 on 2019-06-25 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20190625_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='left_level',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='major',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
