# Generated by Django 2.1.7 on 2019-06-26 13:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20190625_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_first_login',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birth',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(2019), django.core.validators.MinValueValidator(1920)]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='left_level',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='major',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='region',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(8), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='religion',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(4), django.core.validators.MinValueValidator(1)]),
        ),
    ]
