# Generated by Django 2.1.7 on 2019-06-28 15:44

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_profile_is_facebook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image_url',
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='/static/feedpage/default_avatar.png', null=True, upload_to='profile_img'),
        ),
    ]
