# Generated by Django 2.1.7 on 2019-06-29 22:58

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20190629_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='profile_img'),
        ),
    ]
