# Generated by Django 2.1.7 on 2019-06-30 01:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20190630_0758'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
