# Generated by Django 2.1.7 on 2019-06-30 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_profile_profile_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_uuid',
            new_name='uuid',
        ),
    ]
