# Generated by Django 2.1.7 on 2019-04-27 06:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('content_a', models.TextField()),
                ('content_b', models.TextField()),
                ('img_a', models.ImageField(blank=True, null=True, upload_to='')),
                ('img_b', models.ImageField(blank=True, null=True, upload_to='')),
                ('upvote_a', models.IntegerField(default=0)),
                ('upvote_b', models.IntegerField(default=0)),
                ('report', models.IntegerField(default=0)),
                ('editnow', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeedComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('about_a', models.BooleanField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedpage.Feed')),
            ],
        ),
    ]
