# Generated by Django 2.1.7 on 2019-04-02 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='editnow',
            field=models.BooleanField(default=False),
        ),
    ]
