# Generated by Django 2.1.7 on 2019-05-27 06:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_notichecked_at'),
        ('feedpage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noti_type', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_checked', models.BooleanField(default=False)),
                ('feed', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='feedpage.Feed')),
                ('follow', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Follow')),
                ('noti_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='noti_from', to='accounts.Profile')),
                ('noti_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='noti_to', to='accounts.Profile')),
            ],
        ),
    ]
