# Generated by Django 2.1.7 on 2019-05-11 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedpage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='editnow',
        ),
        migrations.AlterField(
            model_name='feed',
            name='img_a',
            field=models.ImageField(blank=True, null=True, upload_to='image_a'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='img_b',
            field=models.ImageField(blank=True, null=True, upload_to='image_b'),
        ),
    ]
