# Generated by Django 2.1.7 on 2019-08-04 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='content_a',
            field=models.CharField(default='', max_length=21),
        ),
        migrations.AlterField(
            model_name='feed',
            name='content_b',
            field=models.CharField(default='', max_length=21),
        ),
        migrations.AlterField(
            model_name='feed',
            name='title',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='feedcomment',
            name='content',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AlterField(
            model_name='upvote',
            name='about_a',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
