# Generated by Django 2.1.7 on 2019-05-27 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedpage', '0002_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_mine',
            field=models.BooleanField(default=False),
        ),
    ]
