# Generated by Django 2.1.7 on 2019-05-15 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedpage', '0002_auto_20190511_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedcomment',
            name='upvote_side',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='feed',
            name='img_a',
            field=models.ImageField(blank=True, null=True, upload_to='img_a'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='img_b',
            field=models.ImageField(blank=True, null=True, upload_to='img_b'),
        ),
    ]
