# Generated by Django 2.1.7 on 2019-04-09 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedpage', '0003_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
