# Generated by Django 2.1.7 on 2019-05-15 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedpage', '0003_auto_20190515_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedcomment',
            name='upvote_side',
            field=models.CharField(default='', max_length=8),
        ),
    ]
