# Generated by Django 2.1.7 on 2019-06-20 16:05

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('feedpage', '0003_notification_is_mine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='img_a',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to='feed_img'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='img_b',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to='feed_img'),
        ),
    ]
