# Generated by Django 2.1.7 on 2019-06-29 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedpage', '0004_auto_20190621_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedcomment',
            name='content',
            field=models.TextField(max_length=69),
        ),
    ]
