# Generated by Django 2.1.7 on 2019-05-15 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedpage', '0004_auto_20190516_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedcomment',
            name='upvote_side',
            field=models.IntegerField(default=0),
        ),
    ]
