# Generated by Django 2.1.7 on 2019-05-15 15:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedpage', '0005_auto_20190516_0004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentupvote',
            old_name='feed_comment',
            new_name='feedcomment',
        ),
        migrations.AlterField(
            model_name='feedcomment',
            name='upvote_users',
            field=models.ManyToManyField(blank=True, related_name='upvote_feedcomments', through='feedpage.CommentUpvote', to=settings.AUTH_USER_MODEL),
        ),
    ]
