# Generated by Django 2.1.7 on 2019-06-29 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedpage', '0006_auto_20190630_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='content_a',
            field=models.CharField(max_length=21),
        ),
        migrations.AlterField(
            model_name='feed',
            name='content_b',
            field=models.CharField(max_length=21),
        ),
    ]
