# Generated by Django 2.1.7 on 2019-05-01 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedpage', '0006_report_reported'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='report_count',
            field=models.IntegerField(default=0),
        ),
    ]
