# Generated by Django 2.1.7 on 2019-05-01 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedpage', '0007_feed_report_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='reported',
        ),
    ]
