# Generated by Django 2.1.7 on 2019-05-01 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedpage', '0008_remove_report_reported'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='upvote_a',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='feed',
            name='upvote_b',
            field=models.IntegerField(default=0),
        ),
    ]
