# Generated by Django 2.1.7 on 2019-06-30 01:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('feedpage', '0008_auto_20190630_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
