# Generated by Django 2.1.7 on 2019-06-30 01:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('feedpage', '0009_auto_20190630_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='feed_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='feed',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
