# Generated by Django 2.1.7 on 2019-06-30 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedpage', '0010_auto_20190630_1021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feed',
            old_name='feed_uuid',
            new_name='uuid',
        ),
    ]
