# Generated by Django 2.1.7 on 2019-05-06 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedpage', '0011_auto_20190506_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentupvote',
            name='total_upvote',
            field=models.IntegerField(default=0),
        ),
    ]
