# Generated by Django 2.1.7 on 2019-07-11 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedpage', '0011_auto_20190630_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='feed_type',
            field=models.IntegerField(default=0),
        ),
    ]
